### PR TITLE
feat(typings) add update method

### LINKED ISSUE #52: update type definition missing
Not sure if this is by design but the update methods type definition is not present in the typings/index.d.ts file nor is it mentioned in the docs.

### PR DESCRIPTION
**Pull request by RealShadowNova**
fixes #52

### CODE REVIEW

**Comment by joelnedev** [comment]
If you say "fixes #52" GitHub will automatically link the issue

**Review by dan-online — COMMENTED** [review]
There's a ton of changes here I assume because of linting, is there a specific line you changed?

**Comment by RealShadowNova** [comment]
> There's a ton of changes here I assume because of linting, is there a specific line you changed?

Yes, prettier never ran in that file apparently so when I saved it formatted. I fixed a comment that lead through half the file. I also added the `update()` method which was missing as said in #52

**Review by dan-online — APPROVED** [review]
LGTM

**Pull request merged**
