### PR TITLE
changed iterator condition

### PR DESCRIPTION
**Pull request by fahimfaisaal**

### CODE REVIEW

**Comment by eslachance** [comment]
Can you explain this change to me? I'm not sure I get why this is necessary.

**Comment by fahimfaisaal** [comment]
From the previous code, we can see, that it's checking the iterable parameter via `typeof` and `equal` operator. is it an iterator or not.

I feel, instead of this, we can take the help of `in` operator. And it's a better approach to check any variable or data that is Iterable or not.

**Comment by eslachance** [comment]
Except the previous code is checking if it's a function or not. Are you 100% certain that in all cases, your change does not break any of the (potential millions of) enmap installations around the world?

**Comment by dan-online** [comment]
Would be easy to check with tests 👀

**Comment by fahimfaisaal** [comment]
```javascript
const isIterable = (iterable) => Symbol.iterator in iterable;
const isIterableOld = (iterable) => typeof iterable[Symbol.iterator] === 'function'

const tests = [[], new Set(), {}, new Map()]

const difference = {
  tests,
  isIterable: tests.map(isIterable),
  isIterableOld: tests.map(isIterableOld)
}

console.table(difference)
```

My test says they are the same.

**Comment by RealShadowNova** [comment]
image

This PR seems valid

**Review by RealShadowNova — APPROVED** [review]

**Review by eslachance — APPROVED** [review]
Just needs to fix the merge conflict and we'll be good to go!

**Pull request merged**
